"""add_qr_enviado_to_bookings

Revision ID: 81e5f713f170
Revises: 4969a5d928dc
Create Date: 2026-05-16 15:03:35.268308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e5f713f170'
down_revision: Union[str, None] = '4969a5d928dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('qr_enviado', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'qr_enviado')
    # ### end Alembic commands ###