"""add_indexes_game_timestamps

Revision ID: fd1b05701cf5
Revises: 81e5f713f170
Create Date: 2026-05-16 15:56:42.444332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1b05701cf5'
down_revision: Union[str, None] = '81e5f713f170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_games_hora_fin_real'), 'games', ['hora_fin_real'], unique=False)
    op.create_index(op.f('ix_games_hora_inicio_real'), 'games', ['hora_inicio_real'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_hora_inicio_real'), table_name='games')
    op.drop_index(op.f('ix_games_hora_fin_real'), table_name='games')
    # ### end Alembic commands ###